# Server configurations
server:
  host: "0.0.0.0"
  httpPort: 8080
  httpsPort: 8443
  caCertPath: "../openssl-cert/ca_chain-bundle.crt"
  caKeyPath: "../openssl-cert/ca_intermediate_unencrypted.key"
  writeTimeout: 15
  readTimeout: 15
  idleTimeout: 60

# Database credentials
#database:
#  user: "admin"
#  pass: "admin"
